kind: pipeline
type: docker
name: build-and-push

environment:
  version: 0.1.0
steps:
- name: build-frontend
  image: node:alpine
  commands:
  - node --version
  - yarn -version
  - cd frontend
  - ls -la
  - yarn
  - yarn build --outDir /result/static/
  - ls -la
  - ls -la /result
  volumes:
  - name: result
    path: /result

- name: build-server
  image: rust:bookworm
  environment:
    CARGO_HOME: /var/cache/drone/cargo
  commands:
  - cargo --version
  - cd server
  - cargo build --release
  - ls -la ./target/release
  - cp ./target/release/nexttodo-server /result
  - ls -la /result
  volumes:
  - name: result
    path: /result
  - name: rust_cache
    path: /var/cache/drone/cargo
 
- name: build docker
  image: docker
  environment:
    CI_REGISTRY_USER:
      from_secret: CI_HUB_USER
    CI_REGISTRY_PASSWORD:
      from_secret: CI_HUB_PASSWORD
    CI_REGISTRY:
      from_secret: CI_REGISTRY
  commands:
  - export VERSION=$version
  - cp -r /result ./
  - chmod a+x result/nexttodo-server
  - ls -la result
  - docker build -t thisseanzhang/nexttodo:$${VERSION} .
  - docker images
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - docker push thisseanzhang/nexttodo:$${VERSION}
  - docker logout $CI_REGISTRY
  - docker rmi thisseanzhang/nexttodo:$${VERSION}
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: result
    path: /result


volumes:
- name: result
  temp: {}
- name: docker
  host:
    path: /var/run/docker.sock
- name: rust_cache
  host:
    path: /tmp/rust_cache
node:
  n114: latest
